/**
 * Property-Based Test: Email Validation Correctness
 * 
 * Feature: blog-frontend, Property 10: Email Validation Correctness
 * For any input string, the validation function SHALL return true if and only if
 * the string matches a valid email format.
 * 
 * Validates: Requirements 11.1, 11.4
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { validateEmail } from '@/lib/utils';

describe('Property Tests: Email Validation', () => {
  /**
   * Property 10: Email Validation Correctness
   * For any valid email address generated by fast-check,
   * validateEmail should return true.
   * 
   * Validates: Requirements 11.1, 11.4
   */
  it('should return true for all valid email addresses', () => {
    fc.assert(
      fc.property(
        fc.emailAddress(),
        (email) => {
          return validateEmail(email) === true;
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 10: Email Validation Correctness
   * For any string without @ symbol, validateEmail should return false.
   * 
   * Validates: Requirements 11.1, 11.4
   */
  it('should return false for strings without @ symbol', () => {
    fc.assert(
      fc.property(
        fc.string().filter(s => !s.includes('@')),
        (invalidEmail) => {
          return validateEmail(invalidEmail) === false;
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 10: Email Validation Correctness
   * For any string with multiple @ symbols, validateEmail should return false.
   * 
   * Validates: Requirements 11.1, 11.4
   */
  it('should return false for strings with multiple @ symbols', () => {
    fc.assert(
      fc.property(
        fc.tuple(fc.string(), fc.string(), fc.string()).map(
          ([a, b, c]) => `${a}@${b}@${c}`
        ),
        (invalidEmail) => {
          return validateEmail(invalidEmail) === false;
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 10: Email Validation Correctness
   * For any string starting with @, validateEmail should return false.
   * 
   * Validates: Requirements 11.1, 11.4
   */
  it('should return false for strings starting with @', () => {
    fc.assert(
      fc.property(
        fc.string().map(s => `@${s}`),
        (invalidEmail) => {
          return validateEmail(invalidEmail) === false;
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 10: Email Validation Correctness
   * For any string ending with @, validateEmail should return false.
   * 
   * Validates: Requirements 11.1, 11.4
   */
  it('should return false for strings ending with @', () => {
    fc.assert(
      fc.property(
        fc.string().map(s => `${s}@`),
        (invalidEmail) => {
          return validateEmail(invalidEmail) === false;
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 10: Email Validation Correctness
   * For any email-like string where domain has no dot,
   * validateEmail should return false.
   * 
   * Validates: Requirements 11.1, 11.4
   */
  it('should return false for email-like strings where domain has no dot', () => {
    fc.assert(
      fc.property(
        fc.tuple(
          fc.string({ minLength: 1 }).filter(s => !s.includes('@') && !s.includes('.')),
          fc.string({ minLength: 1 }).filter(s => !s.includes('@') && !s.includes('.'))
        ).map(([local, domain]) => `${local}@${domain}`),
        (invalidEmail) => {
          return validateEmail(invalidEmail) === false;
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 10: Email Validation Correctness
   * Empty string should always return false.
   * 
   * Validates: Requirements 11.1, 11.4
   */
  it('should return false for empty string', () => {
    expect(validateEmail('')).toBe(false);
  });

  /**
   * Property 10: Email Validation Correctness
   * Whitespace-only strings should return false.
   * 
   * Validates: Requirements 11.1, 11.4
   */
  it('should return false for whitespace-only strings', () => {
    fc.assert(
      fc.property(
        fc.array(fc.constantFrom(' ', '\t', '\n', '\r'), { minLength: 0, maxLength: 10 })
          .map(arr => arr.join('')),
        (whitespace) => {
          return validateEmail(whitespace) === false;
        }
      ),
      { numRuns: 100 }
    );
  });
});
